### PR TITLE
change getting assets name

### PR DESCRIPTION
**Pull request by polearnik**
https://github.com/Elhebert/laravel-mix-sri/issues/2

### CODE REVIEW

**Comment by Elhebert** [comment]
Hi,

I have to find some time to look at this, but at the moment, this package is not a priority for me.

**Comment by Gummibeer** [comment]
@polearnik too keep it a one-liner you can change it to:

```js
let assets = stats.toJson().assets.map(asset => asset.name)
```

**Comment by Gummibeer** [comment]
To fix the `?` problem I've reworked the function to following:

```js
let assets = stats.toJson().assets.map(asset => {
    let name = asset.name
    let i = name.indexOf('?')
    return name.substring(0, i != -1 ? i : name.length)
})
```

**Comment by Elhebert** [comment]
This PR makes no sense to me tbh. 

I used the same object Jeffrey Way does to generate the `manifest.json` in Laravel Mix. (https://github.com/JeffreyWay/laravel-mix/blob/master/src/Manifest.js#L107)

I also have this code used in multiple apps running in productions without any issues.

Could it be that you are both using "exotic" configurations?
Can you give me a working example that reproduces the issue you are trying to solve here?

**Comment by Gummibeer** [comment]
I'm 100% sure that it could be that I did something wrong - but I haven't found anything how to fix it ...

**HbsPlugin**
```js
class HbsPlugin {
    constructor(options) {
        this.options = options
    }

    apply(compiler) {
        compiler.plugin('emit', (compilation, callback) => {
            let plugin = this;
            fs.writeFileSync(plugin.options.target, 'Handlebars.templates = Handlebars.templates || {};\n\n');

            Object.keys(plugin.options.files).map(function (name, index) {
                let relPath = plugin.options.files[name];
                let template = fs.readFileSync(path.resolve(relPath), 'utf8');
                let compiled = Handlebars.precompile(template);
                fs.appendFileSync(plugin.options.target, 'Handlebars.templates[\'' + name + '\'] = Handlebars.template(' + compiled + ');\n\n');
            });

            // I want to get a SRI for this generated file
            compilation.assets['/js/templates.hbs.js'] = {
                source: () => plugin.options.target,
                size: () => fs.statSync(plugin.options.target).size,
            };

            callback();
        })
    }
}
```

**HandlebarsPrecompile**
```js
class HandlebarsPrecompile {
    name() {
        return 'hbs'
    }

    register(options = {}) {
        this.config = {
            enabled: options.enabled || mix.inProduction(),
            target: path.join(require('process').cwd(), 'public/js/templates.hbs.js'),
            files: options.files,
        };
    }

    webpackPlugins() {
        if (this.config.enabled) {
            return new HbsPlugin(this.config)
        }
    }
}
```

**webpack.mix.js**
```js
mix.extend('hbs', new HandlebarsPrecompile());

mix
    .hbs({
        enabled: true,
        files: {
            'app.shooting.file_grid': 'resources/assets/templates/app/shooting/file_grid.hbs',
            'app.shooting.table_row': 'resources/assets/templates/app/shooting/table_row.hbs',
            'app.admin.shooting.table_row': 'resources/assets/templates/app/admin/shooting/table_row.hbs',
            'app.admin.tag.table_row': 'resources/assets/templates/app/admin/tag/table_row.hbs',
            'app.admin.transaction.table_row': 'resources/assets/templates/app/admin/transaction/table_row.hbs',
            'app.admin.user.table_row': 'resources/assets/templates/app/admin/user/table_row.hbs',
            'customer.cart.table_row': 'resources/assets/templates/customer/cart/table_row.hbs',
        }
    })
    .sourceMaps(true, 'source-map')
    .version()
    .generateIntegrityHash({
        enabled: true
    })
;
```

**Comment by Elhebert** [comment]
To be fair, I'm not familiar enough with Webpack for all this, which is why I'm a bit afraid of changing the code.

But I think I'm going to look for a Webpack plugin that generates SRI hashes, and use it instead of my own function. That way, it'll have more chance to work for everyone 🤔

**Comment by Gummibeer** [comment]
Your script works for all Plugins created by pros.^^
So I'm sure that it's me - for the moment I removed the integrity check for this file because I use a very strict CORS.

But the webpack documentation isn't very good if it comes to Plugins. Or it's rly just me who doesn't have any idea what I'm doing as a backend developer!? 😅

**Pull request closed without merging**
