### PR TITLE
Use `Config.publicPath` instead of hardcoding the public path

### PR DESCRIPTION
**Pull request by emzet**
See #14

### CODE REVIEW

**Comment by Elhebert** [comment]
I'll take a look at how the laravel-mix is dealing with this in the Manifest plugin to see if there's things we can actually re-use from there.

**Comment by emzet** [comment]
@Elhebert any update on this?

**Comment by emzet** [comment]
@Elhebert any progress?

**Comment by Elhebert** [comment]
Sorry for the delay.

I don;'t use this package myself so I tend to forget to look at it.

**Pull request merged**
