### PR TITLE
Extend Laravel Mix API object

### PR DESCRIPTION
**Pull request by bram-pkg**

### CODE REVIEW

**Comment by Elhebert** [comment]
I tried to use your solutions, but I don't have any auto completion:
image

You are creating a new interface `Api`, but it's nowhere linked to the actual mix `Api` type. Because of this when typing `mix.ge` you don't have completion for this plugin: 
image


I'm also not sure on why you made changes to the `SriPlugins.ts` file. Could you elaborate the reasoning there? It's not like there's a lot of repetition 🤷

**Comment by bramceulemans** [comment]
To comment on the changes in `SriPlugin.ts`, in older Node.js versions the `readFileSync` throws an error when the file can't be found. I wrote the fallback to empty string because of that.

**Comment by bramceulemans** [comment]
Seems I have to add the `declare namespace` to the types files. Will fix that later.

**Comment by Elhebert** [comment]
I noticed that there's an error on https://github.com/Elhebert/laravel-mix-sri/blob/1ba530d3a6d77e7bc91fda7e879918dd46ce4b8c/src/SriPlugin.ts#L40

It should use the filename there and not the `mix-sri.json` file. I'm going to fix this and publish a new version.
Wouldn't have seen this without your PR 😱 

You can remove that part from this PR to focus only on the types.

**Comment by bramceulemans** [comment]
Alright, I'll remove it.

**Pull request closed without merging**
